#!/usr/bin/env bash

# Determine the current operating system
os=$(uname -s)
arch=$(uname -m)

# Run the appropriate executable based on the OS
case "$os" in
  "Darwin")
    ./binaries/pixi-"$arch"-apple-darwin "$@"
    ;;
  "Linux")
    ./binaries/pixi-"$arch"-unknown-linux-musl "$@"
    ;;
  *)
    echo "Unsupported OS: $os"
    exit 1
    ;;
esac
