#!/usr/bin/env bash

# Determine the current operating system
os=$(uname -s)

# Run the appropriate executable based on the OS
case "$os" in
  "Darwin")
    ./binaries/pixi-aarch64-apple-darwin "$@"
    ;;
  "Linux")
    ./binaries/pixi-x86_64-unknown-linux-musl "$@"
    ;;
  *)
    echo "Unsupported OS: $os"
    exit 1
    ;;
esac
